path_dap: 'C:\Users\SLETIZIA\OneDrive - NREL\Desktop\Main\Custom_functions\dap-py'
path_utils: 'C:\Users\SLETIZIA\OneDrive - NREL\Desktop\Main\utils'
username: 'sletizia'
password: 'pass_DAP1506@'
                